### ISSUE TITLE
Separate new from recently updated

### ISSUE THREAD

**Issue by Raptoer** [Raptoer/FAMDB#25]

**Comment by osarup** [comment]
Paraphrasing comments from Discord:

There are two ways (imo) of doing this:
1. **Separate Tags**
- New = unplayed, working missions (non-broken, non-WIP) on the main server. Maybe "needs revision" ones can be filtered out? Honestly a completely new mission shouldn't need revision, but edge cases and all that. 
- Recently Updated = Working missions on the main server that have been updated after the last played date

2. **Rename "new" to "recently updated"**
- Combines new and recently updated. Hosts can sort by play count to find the unplayed ones.

Not sure which is better/less work/more useful. I could probably use both equally well. Just wondering whether the second method excludes anything that the first would include.

**Comment by Raptoer** [comment]
No longer applicable
