### ISSUE TITLE
Request for transfer/testing system

### ISSUE THREAD

**Issue by Raptoer** [Raptoer/FAMDB#28]

**Comment by osarup** [comment]
Probably good to add WIP and Needs Transfer as tags. I know WIP is probably redundant since "broken" already exists, just that may not be used that way. Alternatively, could rename "broken" to "Broken/WIP".

**Comment by Raptoer** [comment]
Changing to mission status system
"Good"
"Needs Revision"
"Needs transfer"
"Needs testing"
"WIP"
"Broken"

**Comment by Raptoer** [comment]
Done
